name: deploy

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      DD_API_KEY: ${{ secrets.DD_API_KEY }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install cross
        run: cargo install cross --git https://github.com/cross-rs/cross
      - name: Build release binary for ARM64
        run: cross build --release --target aarch64-unknown-linux-gnu
        env:
          OPENSSL_STATIC: 1
          OPENSSL_VENDORED: 1
      - name: Prepare binary for deployment
        run: |
          mkdir -p devops/artifacts
          cp target/aarch64-unknown-linux-gnu/release/gtfs_rt_rater devops/artifacts/
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1
      - name: Generate environment file
        run: |
          cat >> ./devops/.env << EOF
          MOBILITYDATA_REFRESH_TOKEN=${{ secrets.MOBILITYDATA_REFRESH_TOKEN }}
          EOF
      - name: Install Session Manager plugin and boto3
        run: |
          curl "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb" -o "session-manager-plugin.deb"
          sudo dpkg -i session-manager-plugin.deb
          pipx inject ansible-core boto3 botocore
      - name: Run deploy shell script
        run: cd devops && bash ./deploy.sh